# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Buildandpush
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: BuildandPushimage
      inputs:
        containerRegistry: 'dockerhub'
        repository: 'svankad/azurebuild'
        command: buildAndPush
        dockerfile: '**/Dockerfile'
        tags: |
          $(tag)


